version: "3.8"
services:
  db:
    image: mariadb:10.3
    container_name: db
    ports:
      - 3306:3306
    networks:
      - app-db-network
    volumes:
      - ./bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql 
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  app:
    container_name: app
    image: scoma/symfonybookstore:latest
    ports:
      - 80:8000
    depends_on:
      - db
    volumes:
      - app-volume:/app
    environment:
      APP_ENV: prod
      APP_SECRET: 3ee69a49ba88d5db0c8086072b6c6b08 # !
      DATABASE_URL: "mysql://root:secret@db:3306/bookstore"

    networks:
      - app-db-network

volumes:
  db-volume:
    driver: local
  app-volume:
    driver: local

networks:
  app-db-network:
    driver: bridge